name: Terraform Tests

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-tests.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-tests.yml'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  terraform-validate:
    name: Terraform Format & Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layer:
          - bootstrap-oregon
          - layers/01-network
          - layers/02-security
          - layers/03-database
          - layers/04-parameter-store
          - layers/05-cloud-map
          - layers/06-lambda-genai
          - layers/07-application
          - layers/08-api-gateway
          - layers/09-aws-native
          - layers/10-monitoring
          - layers/11-frontend
          - layers/12-notification
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Format Check
        id: fmt
        working-directory: terraform/${{ matrix.layer }}
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init (Backend=false)
        working-directory: terraform/${{ matrix.layer }}
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform/${{ matrix.layer }}
        run: terraform validate

      - name: Comment PR (Format Issues)
        if: github.event_name == 'pull_request' && steps.fmt.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `⚠️ **Terraform Format Check Failed** in \`${{ matrix.layer }}\`\n\nPlease run:\n\`\`\`bash\ncd terraform/${{ matrix.layer }}\nterraform fmt -recursive\n\`\`\``
            })

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layer:
          - bootstrap-oregon
          - layers/01-network
          - layers/02-security
          - layers/03-database
          - layers/04-parameter-store
          - layers/05-cloud-map
          - layers/06-lambda-genai
          - layers/07-application
          - layers/08-api-gateway
          - layers/09-aws-native
          - layers/10-monitoring
          - layers/11-frontend
          - layers/12-notification
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.3

      - name: Initialize TFLint
        working-directory: terraform/${{ matrix.layer }}
        run: tflint --init

      - name: Run TFLint
        working-directory: terraform/${{ matrix.layer }}
        run: tflint --format compact --config ../../.tflint.hcl

  tfsec:
    name: TFSec Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform
          format: sarif,default
          soft_fail: false
          additional_args: --config-file .tfsec.yml --out results.sarif

      - name: Upload TFSec SARIF
        if: always() && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: tfsec

  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/
          framework: terraform
          config_file: terraform/.checkov.yml
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,checkov-results.sarif
        continue-on-error: true

      - name: Upload Checkov SARIF
        if: always() && hashFiles('checkov-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif
          category: checkov

  terraform-docs:
    name: Terraform Docs Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layer:
          - bootstrap-oregon
          - layers/01-network
          - layers/02-security
          - layers/03-database
          - layers/04-parameter-store
          - layers/05-cloud-map
          - layers/06-lambda-genai
          - layers/07-application
          - layers/08-api-gateway
          - layers/09-aws-native
          - layers/10-monitoring
          - layers/11-frontend
          - layers/12-notification
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check README.md exists
        working-directory: terraform/${{ matrix.layer }}
        run: |
          if [ ! -f README.md ]; then
            echo "❌ README.md not found in ${{ matrix.layer }}"
            exit 1
          fi
          echo "✅ README.md exists"

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [terraform-validate, tflint, tfsec, checkov, terraform-docs]
    if: always()
    steps:
      - name: Generate Summary
        run: |
          echo "## Terraform Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Format & Validate | ${{ needs.terraform-validate.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| TFLint | ${{ needs.tflint.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| TFSec | ${{ needs.tfsec.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Checkov | ${{ needs.checkov.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Documentation | ${{ needs.terraform-docs.result }} |" >> $GITHUB_STEP_SUMMARY
