spring:
  application:
    name: api-gateway
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      paramstore:
        enabled: true
        prefix: /petclinic
        profile-separator: /
        fail-fast: false
      secretsmanager:
        enabled: true
        prefix: /petclinic
        fail-fast: false
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: genai-service
          uri: lb://genai-service
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mysql,aws}

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      paramstore:
        enabled: true
        prefix: /petclinic
        profile-separator: /
        fail-fast: false
      secretsmanager:
        enabled: true
        prefix: /petclinic
        fail-fast: false