---
# tfsec configuration file

# Exclude specific checks
exclude:
  # 개발 환경에서 허용되는 보안 예외들
  - aws-s3-enable-bucket-logging
  - aws-s3-enable-versioning
  - aws-s3-specify-public-access-block
  - aws-ec2-no-public-egress-sgr
  - aws-ec2-no-public-ingress-sgr
  - aws-iam-no-policy-wildcards
  - aws-rds-no-public-db-access

# Include only specific checks (선택사항)
# include:
#   - aws-s3-*

# Minimum severity level
minimum-severity: LOW

# Output format
format: default

# Custom checks directory
custom-check-dir: .tfsec/

# Ignore specific paths
ignore-paths:
  - "**/modules/**"  # 모듈은 별도 검토
  - "**/test/**"     # 테스트 파일 제외

# Concise output
concise-output: false

# Include passed checks
include-passed: false

# Include ignored checks
include-ignored: false

# Workspace (for Terraform Cloud/Enterprise)
# workspace: "petclinic-dev"