spring:
  application:
    name: discovery-server
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      paramstore:
        enabled: true
        prefix: /petclinic
        profile-separator: /
        fail-fast: false
      secretsmanager:
        enabled: true
        prefix: /petclinic
        fail-fast: false

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      paramstore:
        enabled: true
        prefix: /petclinic
        profile-separator: /
        fail-fast: false
      secretsmanager:
        enabled: true
        prefix: /petclinic
        fail-fast: false

