name: Terraform Drift Detection

on:
  schedule:
    # 매일 새벽 2시에 실행
    - cron: '0 17 * * *'  # UTC 기준 (KST 02:00)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
        layer: [01-network, 02-security, 03-database, 04-parameter-store, 05-cloud-map, 06-lambda-genai, 07-application, 08-api-gateway, 09-monitoring, 10-aws-native, 11-state-management]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Check for Drift
        id: drift-check
        working-directory: terraform/envs/${{ matrix.environment }}/${{ matrix.layer }}
        run: |
          # Terraform init
          terraform init -upgrade

          # Plan 실행하여 drift 확인
          PLAN_OUTPUT=$(terraform plan -var-file=../../../${{ matrix.environment }}.tfvars -detailed-exitcode 2>&1)
          EXIT_CODE=$?

          # 결과를 파일로 저장
          echo "$PLAN_OUTPUT" > drift-check.txt

          if [ $EXIT_CODE -eq 0 ]; then
            echo "status=no-drift" >> $GITHUB_OUTPUT
            echo "✅ No drift detected in ${{ matrix.environment }}/${{ matrix.layer }}"
          elif [ $EXIT_CODE -eq 1 ]; then
            echo "status=error" >> $GITHUB_OUTPUT
            echo "❌ Error in ${{ matrix.environment }}/${{ matrix.layer }}"
          else
            echo "status=drift-detected" >> $GITHUB_OUTPUT
            echo "⚠️ Drift detected in ${{ matrix.environment }}/${{ matrix.layer }}"
          fi

      - name: Upload Drift Report
        if: steps.drift-check.outputs.status == 'drift-detected' || steps.drift-check.outputs.status == 'error'
        uses: actions/upload-artifact@v4
        with:
          name: drift-report-${{ matrix.environment }}-${{ matrix.layer }}
          path: terraform/envs/${{ matrix.environment }}/${{ matrix.layer }}/drift-check.txt

      - name: Notify Slack on Drift
        if: steps.drift-check.outputs.status == 'drift-detected'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            🚨 *Terraform Drift Detected*

            Environment: `${{ matrix.environment }}`
            Layer: `${{ matrix.layer }}`
            Repository: `${{ github.repository }}`
            Commit: `${{ github.sha }}`

            Please review the drift and update the Terraform configuration accordingly.

            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify on Error
        if: failure()
        run: |
          echo "❌ Drift detection failed for ${{ matrix.environment }}/${{ matrix.layer }}"

  summary:
    runs-on: ubuntu-latest
    needs: drift-detection
    if: always()
    steps:
      - name: Generate Summary
        run: |
          echo "## Drift Detection Summary" >> summary.md
          echo "" >> summary.md
          echo "| Environment | Layer | Status |" >> summary.md
          echo "|-------------|-------|--------|" >> summary.md

          # 각 job의 결과를 요약 (실제 구현에서는 job 결과를 파싱해야 함)
          echo "| dev | All layers | ${{ needs.drift-detection.result }} |" >> summary.md
          echo "| staging | All layers | ${{ needs.drift-detection.result }} |" >> summary.md
          echo "| prod | All layers | ${{ needs.drift-detection.result }} |" >> summary.md

          cat summary.md

      - name: Upload Summary
        uses: actions/upload-artifact@v4
        with:
          name: drift-detection-summary
          path: summary.md