spring:
  main:
    web-application-type: reactive
  application:
    name: genai-service
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      paramstore:
        enabled: true
        prefix: /petclinic
        profile-separator: /
        fail-fast: false
      secretsmanager:
        enabled: true
        prefix: /petclinic
        fail-fast: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mysql,aws}
  ai:
    chat:
      client:
        enabled: true
    # These apply when using spring-ai-azure-openai-spring-boot-starter
    azure:
      openai:
        api-key: ${AZURE_OPENAI_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            temperature: 0.7
            deployment-name: gpt-4o
    # These apply when using spring-ai-openai-spring-boot-starter
    openai:
      api-key: ${OPENAI_API_KEY:demo}
      chat:
        options:
            temperature: 0.7
            model: gpt-4o-mini

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      paramstore:
        enabled: true
        prefix: /petclinic
        profile-separator: /
        fail-fast: false
      secretsmanager:
        enabled: true
        prefix: /petclinic
        fail-fast: false