spring:                   
  cloud:                  
    aws:                  
      servicediscovery:   
        enabled: true     
eureka:
  client:
    serviceUrl:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"