 spring:
   cloud:
     aws:
       region:
         static: ap-northeast-2
       servicediscovery:
         enabled: true
         namespace: petclinic.local
 
 eureka:
   client:
     enabled: false
 
 management:
   endpoints:
     web:
       exposure:
         include: "health,info,prometheus"